version: "1"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: "TicTacToe"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "P@ssw0rd"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3

  frontend:
    build:
      context: ../../mouse-front/mouse-frontend-app
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    depends_on:
      - backend #:
        #condition: service_healthy

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:80
    depends_on:
      - postgres #:
        #condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:80/health"]
      
