apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: my-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: numnummer/muscletraining-frontend:latest
          ports:
            - containerPort: 5173
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: my-project
spec:
  selector:
    app: frontend
  ports:
    - port: 5173
      targetPort: 5173
      nodePort: 30081 # Choose a port between 30000 and 32767
  type: NodePort
