apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: my-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
          env:
            - name: REDIS_PORT
              value: "6379"

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: my-project
spec:
  ports:
    - port: 6379
      targetPort: 6379
      name: redis-port
  selector:
    app: redis
  type: ClusterIP # You can also use "NodePort" for external access, but ClusterIP is sufficient for internal use.
