
name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: ubuntu-latest  

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: "TicTacToe"
          POSTGRES_USER: "postgres"
          POSTGRES_PASSWORD: "P@ssw0rd"
          PGDATA: "/var/lib/postgresql/data/pgdata"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    env:
      Solution_Name: Itis.MyTrainings.Api.sln                         
      Test_Project_Path: Itis.MyTrainings.Api.UnitTests/Itis.MyTrainings.Api.UnitTests.csproj  
      

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore #-warnaserror

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages:  'csharp'

    - name: Autobuild
      uses: github/codeql-action/autobuild@v3

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test             

    - name: Fail if tests fail
      if: ${{ failure() }}
      run: exit 1
